// Put action constants here
// e.g. export const GET_JOB = GET_JOB

// export const SIGNIN_TALENT_REQUEST = 'SIGNIN_TALENT_REQUEST'
// export const SIGNIN_TALENT_SUCCESS = 'SIGNIN_TALENT_SUCCESS'
// export const SIGNIN_TALENT_FAILURE = 'SIGNIN_TALENT_FAILURE'

export const SIGNUP_TALENT_REQUEST = 'SIGNUP_TALENT_REQUEST'
export const SIGNUP_TALENT_SUCCESS = 'SIGNUP_TALENT_SUCCESS'
export const SIGNUP_TALENT_FAILURE = 'SIGNUP_TALENT_FAILURE'
//
// export const LOGOUT_TALENT_REQUEST = 'LOGOUT_TALENT_REQUEST'
// export const LOGOUT_TALENT_SUCCESS = 'LOGOUT_TALENT_SUCCESS'
// export const LOGOUT_TALENT_FAILURE = 'LOGOUT_TALENT_FAILURE'